sudo: false
language: node_js
node_js: '0.12'
install:
- npm prune
- npm install
- npm update
script:
- make travis-lint
- make eslint
- npm test
- npm run build-web
cache:
  directories:
  - node_modules
